---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']
      - id: check-yaml
        exclude: devops/
      - id: end-of-file-fixer

#  - repo: https://github.com/codespell-project/codespell
#    rev: d72317f17295aa1da6527243e443214516017096
#    hooks:
#      - id: codespell
#        args: ['.']

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ['--line-length=120']

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==20.1.4
          - flake8-print==3.1.4

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: "v0.790"
#    hooks:
#      - id: mypy
#        pass_filenames: false
#        args: ['--config-file', 'mypy.ini']
